set(_CATKIN_CURRENT_PACKAGE "rope_rrt")
set(rope_rrt_VERSION "0.0.1")
set(rope_rrt_MAINTAINER "Your Name <youremail@example.com>")
set(rope_rrt_PACKAGE_FORMAT "2")
set(rope_rrt_BUILD_DEPENDS "glog" "roscpp" "std_msgs" "message_runtime" "ompl")
set(rope_rrt_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "message_runtime" "ompl")
set(rope_rrt_BUILDTOOL_DEPENDS "catkin")
set(rope_rrt_BUILDTOOL_EXPORT_DEPENDS )
set(rope_rrt_EXEC_DEPENDS "glog" "roscpp" "std_msgs" "message_runtime" "ompl")
set(rope_rrt_RUN_DEPENDS "glog" "roscpp" "std_msgs" "message_runtime" "ompl")
set(rope_rrt_TEST_DEPENDS "rostest")
set(rope_rrt_DOC_DEPENDS )
set(rope_rrt_URL_WEBSITE "")
set(rope_rrt_URL_BUGTRACKER "")
set(rope_rrt_URL_REPOSITORY "")
set(rope_rrt_DEPRECATED "")